config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :groups, only: [:index, :new, :create] do
    resources :expenses, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_many :expense_groups
  has_many :groups, through: :expense_groups

  validates :name, presence: true
  validates :amount, numericality: true
  validates :amount, presence: { message: 'How much did you spend?' }
end

app/models/expense_group.rb
class ExpenseGroup < ApplicationRecord
  belongs_to :expense
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :expense_groups
  has_many :expenses, through: :expense_groups

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :expenses

  validates :name, presence: { message: 'must not be empty' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :current_page

  def after_sign_in_path_for(_resoure)
    '/groups'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def current_page
    path = request.path.split('/')

    @new_expense = path.last(2) == %w[expenses new]

    @current_page = ''
    path.reverse_each do |page|
      # don't return ids and 'new'
      if page.to_i.zero? and page != 'new'
        @current_page = page
        break
      end
    end
  end

  private

  # overwrite the authenticate_user! so that it shows my splash screen
  # instead of sign_in
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to '/', notice: 'Please sign in to view that page!'
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    @group = Group.find(params[:group_id])
    @expenses = @group.expenses.order(created_at: :desc)
    @total_expenses = 0
    @expenses.each { |expense| @total_expenses += expense.amount }
  end

  def new
    @expense = Expense.new
  end

  def create
    @group = Group.find(params[:group_id])
    @expense = @group.expenses.create(user: current_user, name: params[:expense][:name],
                                      amount: params[:expense][:amount])

    if @expense.errors.none?
      redirect_to group_expenses_path, notice: "#{@expense.name} added successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:user_id, :name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show]
  def index
    @groups = current_user.groups
  end

  def show; end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    if @group.save
      redirect_to groups_path, notice: "#{@group.name} added successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:user_id, :name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/expenses/create.html.erb
<h1>Expenses#create</h1>
<p>Find me in app/views/expenses/create.html.erb</p>

app/views/expenses/index.html.erb
<div class="page-container">
  <section class="flex justify-between items-center ph3 bg-white">
    <p class="light-ash f4"><%= @group.name %></p>
    <p class="card-price"><%= @total_expenses %></p>
  </section>
  <section class="card-bottom ph2">
    <% @expenses.each do |expense| %>
      <article class="card pa2 br2 shadow-5 bg-white mv3">
        <img src=<%= @group.icon %> alt="card-img" class="card-img" />
        <div class="card-details">
          <p><%= expense.name %></p>
          <p class="f7">Purchased <time><%= time_ago_in_words(expense.created_at) %></time></p>
        </div>
        <p class="card-price">$<%= expense.amount %></p>
      </article>
    <% end %>
  </section>

  <%= render partial: 'shared/add_button', locals: {message: 'Add expense', path: new_group_expense_path} %>
  
</div>

app/views/expenses/new.html.erb
<div class="categories-container">
  <section class="card-top bg-white">
    <h1 class="secondary-color">Expenses</h1>
  </section>
  <%= form_with(model: @expense, :html => {:class => 'group-form', :id => 'expense-form'}, url: group_expenses_path, method: :post) do |f|  %>
    <h2 class="pt3 secondary-color">Add an Expense</h2>

    <% if @expense.errors.any? %> 
      <%= render "shared/errors", model: @expense %>
    <% end %>

    <div class="input-block">
      <%= f.text_field :name, placeholder: "Edibles", class: "form-input" %>
    </div>
    <div class="input-block">
      <%= f.text_field :amount, placeholder: "$30.50", class: "form-input" %>
    </div>
    <div class="input-block">
      <%= f.submit class: "btn submit f5 mt4 br2 shadow-5 grow" %>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="page-container">
  <section class="card-top bg-white">
    <h1 class="secondary-color">Categories</h1>
  </section>
  <section class="card-bottom ph2">
    <% @groups.each do |group| %>
      <% total_expenses = 0 %>
      <% group.expenses.each do |expense| %>
        <% total_expenses += expense.amount %>
      <% end %>
      <%= link_to group_expenses_path(group.id), class: "link" do %>
        <article class="card pa2 br2 shadow-5 bg-white mv3">
          <img src=<%= group.icon %> alt="card-img" class="card-img" />
          <div class="card-details">
            <p><%= group.name %></p>
            <p class="f7">Created <time><%= time_ago_in_words(group.created_at) %> ago</time></p>
          </div>
          <p class="card-price">$<%= total_expenses %></p>
        </article>
      <% end %>
    <% end %>
  </section>

  <%= render partial: 'shared/add_button', locals: {message: 'Add category', path: new_group_path} %>

</div>

app/views/groups/new.html.erb
<div class="categories-container">
  <section class="card-top bg-white">
    <h1 class="secondary-color">Categories</h1>
  </section>
  <%= form_with(model: @group, :html => {:class => 'group-form'}, url: groups_path, method: :post) do |f|  %>
    <h2 class="pt3 secondary-color">Add a Category</h2>

    <% if @group.errors.any? %> 
      <%= render "shared/errors", model: @group %>
    <% end %>

    <div class="input-block">
      <%= f.text_field :name, placeholder: "Edibles", class: "form-input" %>
    </div>
    <div class="input-block">
      <%= f.text_field :icon, placeholder: "https://image.url", class: "form-input" %>
    </div>
    <div class="input-block">
      <%= f.submit class: "btn submit f5 mt4 br2 shadow-5 grow"%>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<h1>Group#show</h1>
<p>Find me in app/views/group/show.html.erb</p>

app/views/home/index.html.erb
<section class="card-top bg-white">
  <h1 class="secondary-color">Expense Tracker</h1>
</section>
<section class="card-bottom ph2 flex flex-column items-center justify center">
  <p class="intro-text w-100 w-50-m w-50-l pa2"> Welcome to our free expense tracker. <br>
    Now you can see all the beautiful and, maybe, stupid things you've been spending your money on, 
    organized by categories. 
  </p>
  <%= image_tag 'logo.png', title: 'logo', class: 'logo' %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css"/>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= render 'shared/navbar' %>

    <main class="wrapper">
      <% if notice %>
        <%= render 'shared/alerts' %>
      <% end %>
      
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_add_button.html.erb
<div class="add-btn-block shadow-1 outline-0">
  <%= link_to message, path, class: "add-btn link white" %>
</div>

app/views/shared/_alerts.html.erb
<div class="flex items-center justify-center pa4 bg-lightest-blue navy">
  <svg class="w1" data-icon="info" viewBox="0 0 32 32" style="fill:currentcolor">
    <title>info icon</title>
    <path d="M16 0 A16 16 0 0 1 16 32 A16 16 0 0 1 16 0 M19 15 L13 15 L13 26 L19 26 z M16 6 A3 3 0 0 0 16 12 A3 3 0 0 0 16 6"></path>
  </svg>
  <span class="lh-title ml3"><%= notice %></span>
</div>

app/views/shared/_errors.html.erb
<div style="color: red">
  <p><%= pluralize(model.errors.count, "error") %> need to be addressed</p>
  <ul class="error-list">
    <% model.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<nav class="nav shadow-5">
  <div class="nav-left">

    <% unless user_signed_in? %>
      <%= link_to 'Home', '/', class: 'btn' %>
    <% else %> 
      <%= link_to 'Back', @new_expense ? group_expenses_path : groups_path, class: 'btn' %>
    <% end %>

  </div>
  <div class="nav-mid">
    <p class="page-title"><%= @current_page %></p>
  </div>
  <div class="nav-right">
    <% if user_signed_in? %>
      <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "link white" %>
    <% else %>
      <%= link_to 'Log in', new_user_session_path, class: "btn" %>
    <% end %>
  </div>
</nav>